ol:
  ims:
    project:
      accountImsSdk:
        host: mainframe.openlegacy.com
        port: 9999
        username: DEMO001
        password: Legacy
        code-page: CP037
        data-store-name: IVP1 
        connection-timeout: 5000
        group-name: GROUP1 
        ssl-properties:
          ssl-enabled: false
        transaction-properties:
          commit-mode: COMMIT_AND_SEND
          user-message-exit-identifier: HWSSMPL1
          transaction-timeout: 5000
        connector-type: java
        irm-header:
          irmArch: IRM_ARCH0
          irmArchitecture0:
            irm-f0: irm-f0-default
            irm-id: HWSSMPL1           # User Message Exit
            irm-f5: "42"
            irm-timer: "67"
            irm-client-id: "16580844"
            irm-f1: IRM_F1_NO_MFS
            irm-f2: "COMMIT_THEN_SEND"                     # Commit mode
            irm-f3: NONE
            irm-f4: ACK
            irm-imsdestid: IVP1                     # DataStore
            irm-lterm: "ARIHTER"
            irm-racf-userid: DEMO001                # RACF User
            irm-racf-pw: LEGACY                  # RACF Password
            irm-racf-grname: GROUP1               # RACF Group
  license:
    key: 
