ol:
  mq:
    project:
      mainframeMqSdk:
        hostname: mainframe.openlegacy.com
        port: 1414
        user: 
        password: 
        code-page: CP037
        defaultQueueManager: CSQ9
        channel: CSQ9.SVRCONN
        sendQueue: DEV.OUT.QUEUE
        receiveQueue: DEV.OUT.QUEUE
  license:
    key: 

