package com.policy_cics_api.openlegacy.services;

import org.apache.commons.lang3.StringUtils;
import com.policy_cics_sdk.openlegacy.Lpolcs2;
import com.policy_cics_sdk.openlegacy.Lpolcs2InPut;
import com.policy_cics_sdk.openlegacy.Lpolcs2Lpolcs2Input;
import com.policy_cics_sdk.openlegacy.Lpolcs2Lpolcs2Output;
import com.policy_cics_sdk.openlegacy.Lpolcs2OutPut;
import com.policy_cics_sdk.openlegacy.Lpolcs2PolicyArray;
import org.openlegacy.core.rpc.RpcSession;
import org.openlegacy.core.rpc.actions.RpcActions;

import org.openlegacy.core.annotations.services.*;
import org.openlegacy.core.annotations.OpenlegacyDesigntime;
import org.openlegacy.impl.services.ws.ServiceBinder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.context.ApplicationContext;
import org.openlegacy.utils.ActionUtil;

/**
 *  A service implementation which invokes OpenLegacy API, and returns a service output.
 *  The code below should be customize to perform a working scenario which goes through the relevant screens.
 *  Can be tested by invoking the test ListPolicyServiceTest.
 *  The interface ListPolicyService can be customized to enabling passing parameters to the service, and this class can consume the parameters within the relevant screens.
 */
@Service(name = "ListPolicy")
@OpenlegacyDesigntime(editor = "WebServiceEditor")
@Component
public class ListPolicyServiceImpl implements ListPolicyService {

    @Autowired
    private ApplicationContext applicationContext;


    @Autowired
    private ServiceBinder serviceBinder;

    @Override
    @ServiceMethod(name = "getListPolicy", entities = {
            @EntityMapping(alias="lpolcs2", entity=com.policy_cics_sdk.openlegacy.Lpolcs2.class)})
    @LogServiceUsage
    @BindInputs(endpoints = {
            @BindTo(endpoint = "lpolcs2.lpolcs2Input", expression = "lpolcs2Input")})
    @BindOutputs(endpoints = {
            @BindFrom(endpoint = "lpolcs2Output", expression = "lpolcs2.lpolcs2Output")})
    public ListPolicyOut getListPolicy(ListPolicyIn listPolicyIn) throws Exception {
        ListPolicyOut listPolicyOut = new ListPolicyOut();
        /* autogenerated - sessions block start*/
        ;
        RpcSession policyCicsSdkSession = applicationContext.getBean("policyCicsSdkSession", RpcSession.class);
        /* autogenerated - sessions block end */
        ;

        try {
            /* autogenerated - execution block start */;
            Lpolcs2 lpolcs2 = serviceBinder.bindInputs(this, "getListPolicy", "lpolcs2", new Lpolcs2(), listPolicyIn);
            lpolcs2 = policyCicsSdkSession.doAction(ActionUtil.getRpcAction(Lpolcs2.class), lpolcs2);
            /* autogenerated - execution block end */;

            /* autogenerated - output block start */;
            listPolicyOut = serviceBinder.bindOutput(this, "getListPolicy", listPolicyOut, new String[]{"listPolicyIn", "lpolcs2"}, listPolicyIn, lpolcs2);
            /* autogenerated - output block end */;

            return listPolicyOut;
        } finally {
            /* autogenerated - disconnect block start */
            ;
            policyCicsSdkSession.disconnect();
            /* autogenerated - disconnect block end */
            ;
        }
    }

}
