package com.policy_cics_api.openlegacy.services;

import org.apache.commons.lang3.StringUtils;
import com.policy_cics_sdk.openlegacy.Rpolcs2;
import com.policy_cics_sdk.openlegacy.Rpolcs2InPut;
import com.policy_cics_sdk.openlegacy.Rpolcs2OutPut;
import com.policy_cics_sdk.openlegacy.Rpolcs2PolicyArray;
import com.policy_cics_sdk.openlegacy.Rpolcs2PolicyDetails;
import org.openlegacy.core.rpc.RpcSession;
import org.openlegacy.core.rpc.actions.RpcActions;

import org.openlegacy.core.annotations.services.*;
import org.openlegacy.core.annotations.OpenlegacyDesigntime;
import org.openlegacy.impl.services.ws.ServiceBinder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.context.ApplicationContext;
import org.openlegacy.utils.ActionUtil;

/**
 *  A service implementation which invokes OpenLegacy API, and returns a service output.
 *  The code below should be customize to perform a working scenario which goes through the relevant screens.
 *  Can be tested by invoking the test ResetPolicyServiceTest.
 *  The interface ResetPolicyService can be customized to enabling passing parameters to the service, and this class can consume the parameters within the relevant screens.
 */
@Service(name = "ResetPolicy")
@OpenlegacyDesigntime(editor = "WebServiceEditor")
@Component
public class ResetPolicyServiceImpl implements ResetPolicyService {

    @Autowired
    private ApplicationContext applicationContext;


    @Autowired
    private ServiceBinder serviceBinder;

    @Override
    @ServiceMethod(name = "getResetPolicy", entities = {
            @EntityMapping(alias="rpolcs2", entity=com.policy_cics_sdk.openlegacy.Rpolcs2.class)})
    @LogServiceUsage
    @BindInputs(endpoints = {
            @BindTo(endpoint = "rpolcs2", expression = "rpolcs2")})
    @BindOutputs(endpoints = {
            @BindFrom(endpoint = "rpolcs2", expression = "rpolcs2")})
    public ResetPolicyOut getResetPolicy(ResetPolicyIn resetPolicyIn) throws Exception {
        ResetPolicyOut resetPolicyOut = new ResetPolicyOut();
        /* autogenerated - sessions block start*/
        ;
        RpcSession policyCicsSdkSession = applicationContext.getBean("policyCicsSdkSession", RpcSession.class);
        /* autogenerated - sessions block end */
        ;

        try {
            /* autogenerated - execution block start */;
            Rpolcs2 rpolcs2 = serviceBinder.bindInputs(this, "getResetPolicy", "rpolcs2", new Rpolcs2(), resetPolicyIn);
            rpolcs2 = policyCicsSdkSession.doAction(ActionUtil.getRpcAction(Rpolcs2.class), rpolcs2);
            /* autogenerated - execution block end */;

            /* autogenerated - output block start */;
            resetPolicyOut = serviceBinder.bindOutput(this, "getResetPolicy", resetPolicyOut, new String[]{"resetPolicyIn", "rpolcs2"}, resetPolicyIn, rpolcs2);
            /* autogenerated - output block end */;

            return resetPolicyOut;
        } finally {
            /* autogenerated - disconnect block start */
            ;
            policyCicsSdkSession.disconnect();
            /* autogenerated - disconnect block end */
            ;
        }
    }

}
