package com.policy_cics_api.openlegacy.services;

import org.apache.commons.lang3.StringUtils;
import com.policy_cics_sdk.openlegacy.Upolcs2;
import com.policy_cics_sdk.openlegacy.Upolcs2InPolicy;
import com.policy_cics_sdk.openlegacy.Upolcs2InPut;
import com.policy_cics_sdk.openlegacy.Upolcs2OutPolicy;
import com.policy_cics_sdk.openlegacy.Upolcs2OutPut;
import com.policy_cics_sdk.openlegacy.Upolcs2Upolcs2Input;
import com.policy_cics_sdk.openlegacy.Upolcs2Upolcs2Output;
import org.openlegacy.core.rpc.RpcSession;
import org.openlegacy.core.rpc.actions.RpcActions;

import org.openlegacy.core.annotations.services.*;
import org.openlegacy.core.annotations.OpenlegacyDesigntime;
import org.openlegacy.impl.services.ws.ServiceBinder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.context.ApplicationContext;
import org.openlegacy.utils.ActionUtil;

/**
 *  A service implementation which invokes OpenLegacy API, and returns a service output.
 *  The code below should be customize to perform a working scenario which goes through the relevant screens.
 *  Can be tested by invoking the test UpdatePolicyServiceTest.
 *  The interface UpdatePolicyService can be customized to enabling passing parameters to the service, and this class can consume the parameters within the relevant screens.
 */
@Service(name = "UpdatePolicy")
@OpenlegacyDesigntime(editor = "WebServiceEditor")
@Component
public class UpdatePolicyServiceImpl implements UpdatePolicyService {

    @Autowired
    private ApplicationContext applicationContext;


    @Autowired
    private ServiceBinder serviceBinder;

    @Override
    @ServiceMethod(name = "getUpdatePolicy", entities = {
            @EntityMapping(alias="upolcs2", entity=com.policy_cics_sdk.openlegacy.Upolcs2.class)})
    @LogServiceUsage
    @BindInputs(endpoints = {
            @BindTo(endpoint = "upolcs2.upolcs2Input", expression = "upolcs2Input")})
    @BindOutputs(endpoints = {
            @BindFrom(endpoint = "upolcs2Output", expression = "upolcs2.upolcs2Output")})
    public UpdatePolicyOut getUpdatePolicy(UpdatePolicyIn updatePolicyIn) throws Exception {
        UpdatePolicyOut updatePolicyOut = new UpdatePolicyOut();
        /* autogenerated - sessions block start*/
        ;
        RpcSession policyCicsSdkSession = applicationContext.getBean("policyCicsSdkSession", RpcSession.class);
        /* autogenerated - sessions block end */
        ;

        try {
            /* autogenerated - execution block start */;
            Upolcs2 upolcs2 = serviceBinder.bindInputs(this, "getUpdatePolicy", "upolcs2", new Upolcs2(), updatePolicyIn);
            upolcs2 = policyCicsSdkSession.doAction(ActionUtil.getRpcAction(Upolcs2.class), upolcs2);
            /* autogenerated - execution block end */;

            /* autogenerated - output block start */;
            updatePolicyOut = serviceBinder.bindOutput(this, "getUpdatePolicy", updatePolicyOut, new String[]{"updatePolicyIn", "upolcs2"}, updatePolicyIn, upolcs2);
            /* autogenerated - output block end */;

            return updatePolicyOut;
        } finally {
            /* autogenerated - disconnect block start */
            ;
            policyCicsSdkSession.disconnect();
            /* autogenerated - disconnect block end */
            ;
        }
    }

}
