package com.policy_as400_cobol_api.openlegacy.services;

import org.apache.commons.lang3.StringUtils;
import com.policy_as400_cobol_sdk.openlegacy.POL2OUTL;
import com.policy_as400_cobol_sdk.openlegacy.PgmPolicyOut;
import com.policy_as400_cobol_sdk.openlegacy.PgmPolicyRecOut;
import org.openlegacy.core.rpc.RpcSession;
import org.openlegacy.core.rpc.actions.RpcActions;

import org.openlegacy.core.annotations.services.*;
import org.openlegacy.core.annotations.OpenlegacyDesigntime;
import org.openlegacy.impl.services.ws.ServiceBinder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.context.ApplicationContext;
import org.openlegacy.utils.ActionUtil;

/**
 *  A service implementation which invokes OpenLegacy API, and returns a service output.
 *  The code below should be customize to perform a working scenario which goes through the relevant screens.
 *  The interface AllPoliciesService can be customized to enabling passing parameters to the service, and this class can consume the parameters within the relevant screens.
 */
@Service(name = "AllPolicies")
@OpenlegacyDesigntime(editor = "WebServiceEditor")
@Component
public class AllPoliciesServiceImpl implements AllPoliciesService {

    @Autowired
    private ApplicationContext applicationContext;


    @Autowired
    private ServiceBinder serviceBinder;

    @Override
    @ServiceMethod(name = "getAllPolicies", entities = {
            @EntityMapping(alias="pOL2OUTL", entity=com.policy_as400_cobol_sdk.openlegacy.POL2OUTL.class)})
    @LogServiceUsage
    @BindOutputs(endpoints = {
            @BindFrom(endpoint = "policyOut", expression = "pOL2OUTL.policyOut")})
    public AllPoliciesOut getAllPolicies() throws Exception {
        AllPoliciesOut allPoliciesOut = new AllPoliciesOut();
        /* autogenerated - sessions block start*/
        ;
        RpcSession policyAs400CobolSdkSession = applicationContext.getBean("policyAs400CobolSdkSession", RpcSession.class);
        /* autogenerated - sessions block end */
        ;

        try {
            /* autogenerated - execution block start */;
            POL2OUTL pOL2OUTL = new POL2OUTL();
            pOL2OUTL = policyAs400CobolSdkSession.doAction(ActionUtil.getRpcAction(POL2OUTL.class), pOL2OUTL);
            /* autogenerated - execution block end */;

            /* autogenerated - output block start */;
            allPoliciesOut = serviceBinder.bindOutput(this, "getAllPolicies", allPoliciesOut, new String[]{"pOL2OUTL"}, pOL2OUTL);
            /* autogenerated - output block end */;

            return allPoliciesOut;
        } finally {
            /* autogenerated - disconnect block start */
            ;
            policyAs400CobolSdkSession.disconnect();
            /* autogenerated - disconnect block end */
            ;
        }
    }

}
