package com.policy_as400_cobol_api.openlegacy.services;

import org.apache.commons.lang3.StringUtils;
import com.policy_as400_cobol_sdk.openlegacy.POL2DEL;
import com.policy_as400_cobol_sdk.openlegacy.POL2DELPol2delInput;
import com.policy_as400_cobol_sdk.openlegacy.POL2DELPol2delOutput;
import com.policy_as400_cobol_sdk.openlegacy.POL2DELPolicyRecOut;
import org.openlegacy.core.rpc.RpcSession;
import org.openlegacy.core.rpc.actions.RpcActions;

import org.openlegacy.core.annotations.services.*;
import org.openlegacy.core.annotations.OpenlegacyDesigntime;
import org.openlegacy.impl.services.ws.ServiceBinder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.context.ApplicationContext;
import org.openlegacy.utils.ActionUtil;

/**
 *  A service implementation which invokes OpenLegacy API, and returns a service output.
 *  The code below should be customize to perform a working scenario which goes through the relevant screens.
 *  The interface DeletePolicyService can be customized to enabling passing parameters to the service, and this class can consume the parameters within the relevant screens.
 */
@Service(name = "DeletePolicy")
@OpenlegacyDesigntime(editor = "WebServiceEditor")
@Component
public class DeletePolicyServiceImpl implements DeletePolicyService {

    @Autowired
    private ApplicationContext applicationContext;


    @Autowired
    private ServiceBinder serviceBinder;

    @Override
    @ServiceMethod(name = "getDeletePolicy", entities = {
            @EntityMapping(alias="pOL2DEL", entity=com.policy_as400_cobol_sdk.openlegacy.POL2DEL.class)})
    @LogServiceUsage
    @BindInputs(endpoints = {
            @BindTo(endpoint = "pOL2DEL.pol2delInput", expression = "pol2delInput")})
    @BindOutputs(endpoints = {
            @BindFrom(endpoint = "pol2delOutput", expression = "pOL2DEL.pol2delOutput")})
    public DeletePolicyOut getDeletePolicy(DeletePolicyIn deletePolicyIn) throws Exception {
        DeletePolicyOut deletePolicyOut = new DeletePolicyOut();
        /* autogenerated - sessions block start*/
        ;
        RpcSession policyAs400CobolSdkSession = applicationContext.getBean("policyAs400CobolSdkSession", RpcSession.class);
        /* autogenerated - sessions block end */
        ;

        try {
            /* autogenerated - execution block start */;
            POL2DEL pOL2DEL = serviceBinder.bindInputs(this, "getDeletePolicy", "pOL2DEL", new POL2DEL(), deletePolicyIn);
            pOL2DEL = policyAs400CobolSdkSession.doAction(ActionUtil.getRpcAction(POL2DEL.class), pOL2DEL);
            /* autogenerated - execution block end */;

            /* autogenerated - output block start */;
            deletePolicyOut = serviceBinder.bindOutput(this, "getDeletePolicy", deletePolicyOut, new String[]{"deletePolicyIn", "pOL2DEL"}, deletePolicyIn, pOL2DEL);
            /* autogenerated - output block end */;

            return deletePolicyOut;
        } finally {
            /* autogenerated - disconnect block start */
            ;
            policyAs400CobolSdkSession.disconnect();
            /* autogenerated - disconnect block end */
            ;
        }
    }

}
