package com.policy_as400_cobol_api.openlegacy.services;

import org.apache.commons.lang3.StringUtils;
import com.policy_as400_cobol_sdk.openlegacy.POL2GET;
import com.policy_as400_cobol_sdk.openlegacy.POL2GETPol2getInput;
import com.policy_as400_cobol_sdk.openlegacy.POL2GETPol2getOutput;
import com.policy_as400_cobol_sdk.openlegacy.POL2GETPolicyRecOut;
import org.openlegacy.core.rpc.RpcSession;
import org.openlegacy.core.rpc.actions.RpcActions;

import org.openlegacy.core.annotations.services.*;
import org.openlegacy.core.annotations.OpenlegacyDesigntime;
import org.openlegacy.impl.services.ws.ServiceBinder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.context.ApplicationContext;
import org.openlegacy.utils.ActionUtil;

/**
 *  A service implementation which invokes OpenLegacy API, and returns a service output.
 *  The code below should be customize to perform a working scenario which goes through the relevant screens.
 *  The interface GetPolicyService can be customized to enabling passing parameters to the service, and this class can consume the parameters within the relevant screens.
 */
@Service(name = "GetPolicy")
@OpenlegacyDesigntime(editor = "WebServiceEditor")
@Component
public class GetPolicyServiceImpl implements GetPolicyService {

    @Autowired
    private ApplicationContext applicationContext;


    @Autowired
    private ServiceBinder serviceBinder;

    @Override
    @ServiceMethod(name = "getGetPolicy", entities = {
            @EntityMapping(alias="pOL2GET", entity=com.policy_as400_cobol_sdk.openlegacy.POL2GET.class)})
    @LogServiceUsage
    @BindInputs(endpoints = {
            @BindTo(endpoint = "pOL2GET.pol2getInput", expression = "pol2getInput")})
    @BindOutputs(endpoints = {
            @BindFrom(endpoint = "pol2getOutput", expression = "pOL2GET.pol2getOutput")})
    public GetPolicyOut getGetPolicy(GetPolicyIn getPolicyIn) throws Exception {
        GetPolicyOut getPolicyOut = new GetPolicyOut();
        /* autogenerated - sessions block start*/
        ;
        RpcSession policyAs400CobolSdkSession = applicationContext.getBean("policyAs400CobolSdkSession", RpcSession.class);
        /* autogenerated - sessions block end */
        ;

        try {
            /* autogenerated - execution block start */;
            POL2GET pOL2GET = serviceBinder.bindInputs(this, "getGetPolicy", "pOL2GET", new POL2GET(), getPolicyIn);
            pOL2GET = policyAs400CobolSdkSession.doAction(ActionUtil.getRpcAction(POL2GET.class), pOL2GET);
            /* autogenerated - execution block end */;

            /* autogenerated - output block start */;
            getPolicyOut = serviceBinder.bindOutput(this, "getGetPolicy", getPolicyOut, new String[]{"getPolicyIn", "pOL2GET"}, getPolicyIn, pOL2GET);
            /* autogenerated - output block end */;

            return getPolicyOut;
        } finally {
            /* autogenerated - disconnect block start */
            ;
            policyAs400CobolSdkSession.disconnect();
            /* autogenerated - disconnect block end */
            ;
        }
    }

}
