package com.policy_as400_cobol_api.openlegacy.services;

import org.apache.commons.lang3.StringUtils;
import com.policy_as400_cobol_sdk.openlegacy.POL2UPD;
import com.policy_as400_cobol_sdk.openlegacy.POL2UPDPol2updInput;
import com.policy_as400_cobol_sdk.openlegacy.POL2UPDPol2updOutput;
import com.policy_as400_cobol_sdk.openlegacy.POL2UPDPolicyRecOut;
import org.openlegacy.core.rpc.RpcSession;
import org.openlegacy.core.rpc.actions.RpcActions;

import org.openlegacy.core.annotations.services.*;
import org.openlegacy.core.annotations.OpenlegacyDesigntime;
import org.openlegacy.impl.services.ws.ServiceBinder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.context.ApplicationContext;
import org.openlegacy.utils.ActionUtil;

/**
 *  A service implementation which invokes OpenLegacy API, and returns a service output.
 *  The code below should be customize to perform a working scenario which goes through the relevant screens.
 *  The interface UpdatePolicyService can be customized to enabling passing parameters to the service, and this class can consume the parameters within the relevant screens.
 */
@Service(name = "UpdatePolicy")
@OpenlegacyDesigntime(editor = "WebServiceEditor")
@Component
public class UpdatePolicyServiceImpl implements UpdatePolicyService {

    @Autowired
    private ApplicationContext applicationContext;


    @Autowired
    private ServiceBinder serviceBinder;

    @Override
    @ServiceMethod(name = "getUpdatePolicy", entities = {
            @EntityMapping(alias="pOL2UPD", entity=com.policy_as400_cobol_sdk.openlegacy.POL2UPD.class)})
    @LogServiceUsage
    @BindInputs(endpoints = {
            @BindTo(endpoint = "pOL2UPD.pol2updInput", expression = "pol2updInput")})
    @BindOutputs(endpoints = {
            @BindFrom(endpoint = "pol2updOutput", expression = "pOL2UPD.pol2updOutput")})
    public UpdatePolicyOut getUpdatePolicy(UpdatePolicyIn updatePolicyIn) throws Exception {
        UpdatePolicyOut updatePolicyOut = new UpdatePolicyOut();
        /* autogenerated - sessions block start*/
        ;
        RpcSession policyAs400CobolSdkSession = applicationContext.getBean("policyAs400CobolSdkSession", RpcSession.class);
        /* autogenerated - sessions block end */
        ;

        try {
            /* autogenerated - execution block start */;
            POL2UPD pOL2UPD = serviceBinder.bindInputs(this, "getUpdatePolicy", "pOL2UPD", new POL2UPD(), updatePolicyIn);
            pOL2UPD = policyAs400CobolSdkSession.doAction(ActionUtil.getRpcAction(POL2UPD.class), pOL2UPD);
            /* autogenerated - execution block end */;

            /* autogenerated - output block start */;
            updatePolicyOut = serviceBinder.bindOutput(this, "getUpdatePolicy", updatePolicyOut, new String[]{"updatePolicyIn", "pOL2UPD"}, updatePolicyIn, pOL2UPD);
            /* autogenerated - output block end */;

            return updatePolicyOut;
        } finally {
            /* autogenerated - disconnect block start */
            ;
            policyAs400CobolSdkSession.disconnect();
            /* autogenerated - disconnect block end */
            ;
        }
    }

}
