---
ol:
  config:
    apiSourceFolder: "src/main/java"
    apiPackage: "com.account_as400_pcml_sdk.openlegacy"
    webPackage: "com.account_as400_pcml_sdk.openlegacy.web"
    generateTest: true
    provider: "openlegacy-jt400"
    sourceFetcher: "sourceFetcher"
    designtimeContext: "default"
    backendSolution: "AS400_RPC"
    frontendSolution: "JAVA"
    db2Type: "NONE"
    rpc:
      generateRpcPartAsExternalClass: true
    additionalProperties: {}
    designtime:
      parser:
        cobol:
          addMissedDots: false
          handleDuplicateNames: false
        wsdl:
          removeNamespaceTrailingSlash: false
        pli:
          getDirectionByFieldNamePattern: false
          inputFieldPattern: ""
          outputFieldPattern: ""
        csv:
          delimiter: ","
      mapping:
        converters: []
      advancedParameters: []
    swagger:
      updateConfigInfoFromContractFile: true
    file:
      defaultStringLength: 255
    modules: {}
