package com.policy_db2_api.openlegacy.services;

import org.apache.commons.lang3.StringUtils;
import com.policy_db2_sdk.openlegacy.Gpolsql;
import com.policy_db2_sdk.openlegacy.Gpolsql.ResultSet;
import org.openlegacy.core.rpc.RpcSession;
import org.openlegacy.core.rpc.actions.RpcActions;

import org.openlegacy.core.annotations.services.*;
import org.openlegacy.core.annotations.OpenlegacyDesigntime;
import org.openlegacy.impl.services.ws.ServiceBinder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.context.ApplicationContext;
import org.openlegacy.utils.ActionUtil;

/**
 *  A service implementation which invokes OpenLegacy API, and returns a service output.
 *  The code below should be customize to perform a working scenario which goes through the relevant screens.
 *  Can be tested by invoking the test GetPolicyServiceTest.
 *  The interface GetPolicyService can be customized to enabling passing parameters to the service, and this class can consume the parameters within the relevant screens.
 */
@Service(name = "GetPolicy")
@OpenlegacyDesigntime(editor = "WebServiceEditor")
@Component
public class GetPolicyServiceImpl implements GetPolicyService {

    @Autowired
    private ApplicationContext applicationContext;


    @Autowired
    private ServiceBinder serviceBinder;

    @Override
    @ServiceMethod(name = "getGetPolicy", entities = {
            @EntityMapping(alias="gpolsql", entity=com.policy_db2_sdk.openlegacy.Gpolsql.class)})
    @LogServiceUsage
    @BindInputs(endpoints = {
            @BindTo(endpoint = "gpolsql.policyNum", expression = "policyNum")})
    @BindOutputs(endpoints = {
            @BindFrom(endpoint = "resultSet", expression = "gpolsql.resultSet")})
    public GetPolicyOut getGetPolicy(GetPolicyIn getPolicyIn) throws Exception {
        GetPolicyOut getPolicyOut = new GetPolicyOut();
        /* autogenerated - sessions block start*/
        ;
        RpcSession policyDb2SdkSession = applicationContext.getBean("policyDb2SdkSession", RpcSession.class);
        /* autogenerated - sessions block end */
        ;

        try {
            /* autogenerated - execution block start */;
            Gpolsql gpolsql = serviceBinder.bindInputs(this, "getGetPolicy", "gpolsql", new Gpolsql(), getPolicyIn);
            gpolsql = policyDb2SdkSession.doAction(ActionUtil.getRpcAction(Gpolsql.class), gpolsql);
            /* autogenerated - execution block end */;

            /* autogenerated - output block start */;
            getPolicyOut = serviceBinder.bindOutput(this, "getGetPolicy", getPolicyOut, new String[]{"getPolicyIn", "gpolsql"}, getPolicyIn, gpolsql);
            /* autogenerated - output block end */;

            return getPolicyOut;
        } finally {
            /* autogenerated - disconnect block start */
            ;
            policyDb2SdkSession.disconnect();
            /* autogenerated - disconnect block end */
            ;
        }
    }

}
