package com.policy_db2_api.openlegacy.services;

import org.apache.commons.lang3.StringUtils;
import com.policy_db2_sdk.openlegacy.Opolsql;
import java.math.BigDecimal;
import org.openlegacy.core.rpc.RpcSession;
import org.openlegacy.core.rpc.actions.RpcActions;

import org.openlegacy.core.annotations.services.*;
import org.openlegacy.core.annotations.OpenlegacyDesigntime;
import org.openlegacy.impl.services.ws.ServiceBinder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.context.ApplicationContext;
import org.openlegacy.utils.ActionUtil;

/**
 *  A service implementation which invokes OpenLegacy API, and returns a service output.
 *  The code below should be customize to perform a working scenario which goes through the relevant screens.
 *  Can be tested by invoking the test OpenPolicyServiceTest.
 *  The interface OpenPolicyService can be customized to enabling passing parameters to the service, and this class can consume the parameters within the relevant screens.
 */
@Service(name = "OpenPolicy")
@OpenlegacyDesigntime(editor = "WebServiceEditor")
@Component
public class OpenPolicyServiceImpl implements OpenPolicyService {

    @Autowired
    private ApplicationContext applicationContext;


    @Autowired
    private ServiceBinder serviceBinder;

    @Override
    @ServiceMethod(name = "getOpenPolicy", entities = {
            @EntityMapping(alias="opolsql", entity=com.policy_db2_sdk.openlegacy.Opolsql.class)})
    @LogServiceUsage
    @BindInputs(endpoints = {
            @BindTo(endpoint = "opolsql.policyNum", expression = "policyNum"),
            @BindTo(endpoint = "opolsql.custName", expression = "custName"),
            @BindTo(endpoint = "opolsql.custAddr", expression = "custAddr"),
            @BindTo(endpoint = "opolsql.custCity", expression = "custCity"),
            @BindTo(endpoint = "opolsql.custState", expression = "custState"),
            @BindTo(endpoint = "opolsql.custZip", expression = "custZip"),
            @BindTo(endpoint = "opolsql.custPhone", expression = "custPhone"),
            @BindTo(endpoint = "opolsql.birthDate", expression = "birthDate"),
            @BindTo(endpoint = "opolsql.createDate", expression = "createDate"),
            @BindTo(endpoint = "opolsql.endDate", expression = "endDate"),
            @BindTo(endpoint = "opolsql.policyType", expression = "policyType"),
            @BindTo(endpoint = "opolsql.monthlyPymt", expression = "monthlyPymt"),
            @BindTo(endpoint = "opolsql.quarterlyPymt", expression = "quarterlyPymt"),
            @BindTo(endpoint = "opolsql.yearlyPymt", expression = "yearlyPymt"),
            @BindTo(endpoint = "opolsql.isactive", expression = "isactive")})
    @BindOutputs(endpoints = {
            @BindFrom(endpoint = "policyNum", expression = "opolsql.policyNum"),
            @BindFrom(endpoint = "custName", expression = "opolsql.custName"),
            @BindFrom(endpoint = "custAddr", expression = "opolsql.custAddr"),
            @BindFrom(endpoint = "custCity", expression = "opolsql.custCity"),
            @BindFrom(endpoint = "custState", expression = "opolsql.custState"),
            @BindFrom(endpoint = "custZip", expression = "opolsql.custZip"),
            @BindFrom(endpoint = "custPhone", expression = "opolsql.custPhone"),
            @BindFrom(endpoint = "birthDate", expression = "opolsql.birthDate"),
            @BindFrom(endpoint = "createDate", expression = "opolsql.createDate"),
            @BindFrom(endpoint = "endDate", expression = "opolsql.endDate"),
            @BindFrom(endpoint = "policyType", expression = "opolsql.policyType"),
            @BindFrom(endpoint = "monthlyPymt", expression = "opolsql.monthlyPymt"),
            @BindFrom(endpoint = "quarterlyPymt", expression = "opolsql.quarterlyPymt"),
            @BindFrom(endpoint = "yearlyPymt", expression = "opolsql.yearlyPymt"),
            @BindFrom(endpoint = "isactive", expression = "opolsql.isactive")})
    public OpenPolicyOut getOpenPolicy(OpenPolicyIn openPolicyIn) throws Exception {
        OpenPolicyOut openPolicyOut = new OpenPolicyOut();
        /* autogenerated - sessions block start*/
        ;
        RpcSession policyDb2SdkSession = applicationContext.getBean("policyDb2SdkSession", RpcSession.class);
        /* autogenerated - sessions block end */
        ;

        try {
            /* autogenerated - execution block start */;
            Opolsql opolsql = serviceBinder.bindInputs(this, "getOpenPolicy", "opolsql", new Opolsql(), openPolicyIn);
            opolsql = policyDb2SdkSession.doAction(ActionUtil.getRpcAction(Opolsql.class), opolsql);
            /* autogenerated - execution block end */;

            /* autogenerated - output block start */;
            openPolicyOut = serviceBinder.bindOutput(this, "getOpenPolicy", openPolicyOut, new String[]{"openPolicyIn", "opolsql"}, openPolicyIn, opolsql);
            /* autogenerated - output block end */;

            return openPolicyOut;
        } finally {
            /* autogenerated - disconnect block start */
            ;
            policyDb2SdkSession.disconnect();
            /* autogenerated - disconnect block end */
            ;
        }
    }

}
