package com.policy_db2_api.openlegacy.services;

import org.apache.commons.lang3.StringUtils;
import com.policy_db2_sdk.openlegacy.Rpolsql;
import org.openlegacy.core.rpc.RpcSession;
import org.openlegacy.core.rpc.actions.RpcActions;

import org.openlegacy.core.annotations.services.*;
import org.openlegacy.core.annotations.OpenlegacyDesigntime;
import org.openlegacy.impl.services.ws.ServiceBinder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.context.ApplicationContext;
import org.openlegacy.utils.ActionUtil;

/**
 *  A service implementation which invokes OpenLegacy API, and returns a service output.
 *  The code below should be customize to perform a working scenario which goes through the relevant screens.
 *  Can be tested by invoking the test ResetAccountServiceTest.
 *  The interface ResetAccountService can be customized to enabling passing parameters to the service, and this class can consume the parameters within the relevant screens.
 */
@Service(name = "ResetAccount")
@OpenlegacyDesigntime(editor = "WebServiceEditor")
@Component
public class ResetAccountServiceImpl implements ResetAccountService {

    @Autowired
    private ApplicationContext applicationContext;


    @Autowired
    private ServiceBinder serviceBinder;

    @Override
    @ServiceMethod(name = "getResetAccount", entities = {
            @EntityMapping(alias="rpolsql", entity=com.policy_db2_sdk.openlegacy.Rpolsql.class)})
    @LogServiceUsage
    @BindInputs(endpoints = {
            @BindTo(endpoint = "rpolsql", expression = "rpolsql")})
    @BindOutputs(endpoints = {
            @BindFrom(endpoint = "rpolsql", expression = "rpolsql")})
    public ResetAccountOut getResetAccount(ResetAccountIn resetAccountIn) throws Exception {
        ResetAccountOut resetAccountOut = new ResetAccountOut();
        /* autogenerated - sessions block start*/
        ;
        RpcSession policyDb2SdkSession = applicationContext.getBean("policyDb2SdkSession", RpcSession.class);
        /* autogenerated - sessions block end */
        ;

        try {
            /* autogenerated - execution block start */;
            Rpolsql rpolsql = serviceBinder.bindInputs(this, "getResetAccount", "rpolsql", new Rpolsql(), resetAccountIn);
            rpolsql = policyDb2SdkSession.doAction(ActionUtil.getRpcAction(Rpolsql.class), rpolsql);
            /* autogenerated - execution block end */;

            /* autogenerated - output block start */;
            resetAccountOut = serviceBinder.bindOutput(this, "getResetAccount", resetAccountOut, new String[]{"resetAccountIn", "rpolsql"}, resetAccountIn, rpolsql);
            /* autogenerated - output block end */;

            return resetAccountOut;
        } finally {
            /* autogenerated - disconnect block start */
            ;
            policyDb2SdkSession.disconnect();
            /* autogenerated - disconnect block end */
            ;
        }
    }

}
