package com.account_oracle_api.openlegacy.services;

import org.apache.commons.lang3.StringUtils;
import com.account_oracle_sdk.openlegacy.GetAccount;
import com.account_oracle_sdk.openlegacy.GetAccount.BankAccountObj;
import org.openlegacy.core.rpc.RpcSession;
import org.openlegacy.core.rpc.actions.RpcActions;

import org.openlegacy.core.annotations.services.*;
import org.openlegacy.core.annotations.OpenlegacyDesigntime;
import org.openlegacy.impl.services.ws.ServiceBinder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.context.ApplicationContext;
import org.openlegacy.utils.ActionUtil;

/**
 *  A service implementation which invokes OpenLegacy API, and returns a service output.
 *  The code below should be customize to perform a working scenario which goes through the relevant screens.
 *  The interface GetAccountService can be customized to enabling passing parameters to the service, and this class can consume the parameters within the relevant screens.
 */
@Service(name = "GetAccount")
@OpenlegacyDesigntime(editor = "WebServiceEditor")
@Component
public class GetAccountServiceImpl implements GetAccountService {

    @Autowired
    private ApplicationContext applicationContext;


    @Autowired
    private ServiceBinder serviceBinder;

    @Override
    @ServiceMethod(name = "getGetAccount", entities = {
            @EntityMapping(alias="getAccount", entity=com.account_oracle_sdk.openlegacy.GetAccount.class)})
    @LogServiceUsage
    @BindInputs(endpoints = {
            @BindTo(endpoint = "getAccount.paccountId", expression = "paccountId")})
    @BindOutputs(endpoints = {
            @BindFrom(endpoint = "pbankAccountObj", expression = "getAccount.pbankAccountObj")})
    public GetAccountOut getGetAccount(GetAccountIn getAccountIn) throws Exception {
        GetAccountOut getAccountOut = new GetAccountOut();
        /* autogenerated - sessions block start*/
        ;
        RpcSession accountOracleSdkSession = applicationContext.getBean("accountOracleSdkSession", RpcSession.class);
        /* autogenerated - sessions block end */
        ;

        try {
            /* autogenerated - execution block start */;
            GetAccount getAccount = serviceBinder.bindInputs(this, "getGetAccount", "getAccount", new GetAccount(), getAccountIn);
            getAccount = accountOracleSdkSession.doAction(ActionUtil.getRpcAction(GetAccount.class), getAccount);
            /* autogenerated - execution block end */;

            /* autogenerated - output block start */;
            getAccountOut = serviceBinder.bindOutput(this, "getGetAccount", getAccountOut, new String[]{"getAccountIn", "getAccount"}, getAccountIn, getAccount);
            /* autogenerated - output block end */;

            return getAccountOut;
        } finally {
            /* autogenerated - disconnect block start */
            ;
            accountOracleSdkSession.disconnect();
            /* autogenerated - disconnect block end */
            ;
        }
    }

}
