package com.account_oracle_api.openlegacy.services;

import org.apache.commons.lang3.StringUtils;
import com.account_oracle_sdk.openlegacy.OpenAccount;
import com.account_oracle_sdk.openlegacy.OpenAccount.BankAccountObj;
import java.math.BigDecimal;
import org.openlegacy.core.rpc.RpcSession;
import org.openlegacy.core.rpc.actions.RpcActions;

import org.openlegacy.core.annotations.services.*;
import org.openlegacy.core.annotations.OpenlegacyDesigntime;
import org.openlegacy.impl.services.ws.ServiceBinder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.context.ApplicationContext;
import org.openlegacy.utils.ActionUtil;

/**
 *  A service implementation which invokes OpenLegacy API, and returns a service output.
 *  The code below should be customize to perform a working scenario which goes through the relevant screens.
 *  The interface OpenAccountService can be customized to enabling passing parameters to the service, and this class can consume the parameters within the relevant screens.
 */
@Service(name = "OpenAccount")
@OpenlegacyDesigntime(editor = "WebServiceEditor")
@Component
public class OpenAccountServiceImpl implements OpenAccountService {

    @Autowired
    private ApplicationContext applicationContext;


    @Autowired
    private ServiceBinder serviceBinder;

    @Override
    @ServiceMethod(name = "getOpenAccount", entities = {
            @EntityMapping(alias="openAccount", entity=com.account_oracle_sdk.openlegacy.OpenAccount.class)})
    @LogServiceUsage
    @BindInputs(endpoints = {
            @BindTo(endpoint = "openAccount.paccountId", expression = "paccountId"),
            @BindTo(endpoint = "openAccount.pcustomerId", expression = "pcustomerId"),
            @BindTo(endpoint = "openAccount.pcustomerName", expression = "pcustomerName"),
            @BindTo(endpoint = "openAccount.piban", expression = "piban"),
            @BindTo(endpoint = "openAccount.pcountryCode", expression = "pcountryCode"),
            @BindTo(endpoint = "openAccount.pbankId", expression = "pbankId"),
            @BindTo(endpoint = "openAccount.pbrnchId", expression = "pbrnchId"),
            @BindTo(endpoint = "openAccount.ptypcd", expression = "ptypcd"),
            @BindTo(endpoint = "openAccount.ptypeName", expression = "ptypeName"),
            @BindTo(endpoint = "openAccount.psubTypcd", expression = "psubTypcd"),
            @BindTo(endpoint = "openAccount.ptypeDescription", expression = "ptypeDescription"),
            @BindTo(endpoint = "openAccount.pbalance", expression = "pbalance"),
            @BindTo(endpoint = "openAccount.pcurrency", expression = "pcurrency"),
            @BindTo(endpoint = "openAccount.plocked", expression = "plocked")})
    @BindOutputs(endpoints = {
            @BindFrom(endpoint = "bankAccountObj", expression = "openAccount.bankAccountObj")})
    public OpenAccountOut getOpenAccount(OpenAccountIn openAccountIn) throws Exception {
        OpenAccountOut openAccountOut = new OpenAccountOut();
        /* autogenerated - sessions block start*/
        ;
        RpcSession accountOracleSdkSession = applicationContext.getBean("accountOracleSdkSession", RpcSession.class);
        /* autogenerated - sessions block end */
        ;

        try {
            /* autogenerated - execution block start */;
            OpenAccount openAccount = serviceBinder.bindInputs(this, "getOpenAccount", "openAccount", new OpenAccount(), openAccountIn);
            openAccount = accountOracleSdkSession.doAction(ActionUtil.getRpcAction(OpenAccount.class), openAccount);
            /* autogenerated - execution block end */;

            /* autogenerated - output block start */;
            openAccountOut = serviceBinder.bindOutput(this, "getOpenAccount", openAccountOut, new String[]{"openAccountIn", "openAccount"}, openAccountIn, openAccount);
            /* autogenerated - output block end */;

            return openAccountOut;
        } finally {
            /* autogenerated - disconnect block start */
            ;
            accountOracleSdkSession.disconnect();
            /* autogenerated - disconnect block end */
            ;
        }
    }

}
