---
ol:
  config:
    apiSourceFolder: "src/main/java"
    apiPackage: "com.mainframe_s3270_api.openlegacy"
    webPackage: "com.mainframe_s3270_api.openlegacy.web"
    sourceFetcher: "sourceFetcher"
    designtimeContext: "default"
    backendSolution: "ORCHESTRATION"
    frontendSolution: "ORCHESTRATION_REST"
    referredProjects:
    - "mf-screens-sdk"
    db2Type: "NONE"
    rpc:
      generateRpcPartAsExternalClass: true
    additionalProperties: {}
    designtime:
      parser:
        cobol:
          addMissedDots: false
          handleDuplicateNames: false
        wsdl:
          removeNamespaceTrailingSlash: false
        pli:
          getDirectionByFieldNamePattern: false
          inputFieldPattern: ""
          outputFieldPattern: ""
        csv:
          delimiter: ","
      mapping:
        converters: []
      advancedParameters: []
    swagger:
      updateConfigInfoFromContractFile: true
    file:
      defaultStringLength: 255
    modules: {}
