package com.account_ims_api.openlegacy.services;

import org.apache.commons.lang3.StringUtils;
import com.account_ims_sdk.openlegacy.Gactim8;
import com.account_ims_sdk.openlegacy.Gactim8AccountOut;
import com.account_ims_sdk.openlegacy.Gactim8Gactim8Input;
import com.account_ims_sdk.openlegacy.Gactim8Gactim8Output;
import org.openlegacy.core.rpc.RpcSession;
import org.openlegacy.core.rpc.actions.RpcActions;

import org.openlegacy.core.annotations.services.*;
import org.openlegacy.core.annotations.OpenlegacyDesigntime;
import org.openlegacy.impl.services.ws.ServiceBinder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.context.ApplicationContext;
import org.openlegacy.utils.ActionUtil;

/**
 *  A service implementation which invokes OpenLegacy API, and returns a service output.
 *  The code below should be customize to perform a working scenario which goes through the relevant screens.
 *  The interface GetAccountService can be customized to enabling passing parameters to the service, and this class can consume the parameters within the relevant screens.
 */
@Service(name = "GetAccount")
@OpenlegacyDesigntime(editor = "WebServiceEditor")
@Component
public class GetAccountServiceImpl implements GetAccountService {

    @Autowired
    private ApplicationContext applicationContext;


    @Autowired
    private ServiceBinder serviceBinder;

    @Override
    @ServiceMethod(name = "getGetAccount", entities = {
            @EntityMapping(alias="gactim8", entity=com.account_ims_sdk.openlegacy.Gactim8.class)})
    @LogServiceUsage
    @BindInputs(endpoints = {
            @BindTo(endpoint = "gactim8.gactim8Input", expression = "gactim8Input")})
    @BindOutputs(endpoints = {
            @BindFrom(endpoint = "gactim8Output", expression = "gactim8.gactim8Output")})
    public GetAccountOut getGetAccount(GetAccountIn getAccountIn) throws Exception {
        GetAccountOut getAccountOut = new GetAccountOut();
        /* autogenerated - sessions block start*/
        ;
        RpcSession accountImsSdkSession = applicationContext.getBean("accountImsSdkSession", RpcSession.class);
        /* autogenerated - sessions block end */
        ;

        try {
            /* autogenerated - execution block start */;
            Gactim8 gactim8 = serviceBinder.bindInputs(this, "getGetAccount", "gactim8", new Gactim8(), getAccountIn);
            gactim8 = accountImsSdkSession.doAction(ActionUtil.getRpcAction(Gactim8.class), gactim8);
            /* autogenerated - execution block end */;

            /* autogenerated - output block start */;
            getAccountOut = serviceBinder.bindOutput(this, "getGetAccount", getAccountOut, new String[]{"getAccountIn", "gactim8"}, getAccountIn, gactim8);
            /* autogenerated - output block end */;

            return getAccountOut;
        } finally {
            /* autogenerated - disconnect block start */
            ;
            accountImsSdkSession.disconnect();
            /* autogenerated - disconnect block end */
            ;
        }
    }

}
