package com.account_cics_api.openlegacy.services;

import org.apache.commons.lang3.StringUtils;
import com.account_cics_sdk.openlegacy.Dactcs9;
import com.account_cics_sdk.openlegacy.Dactcs9AccountDetails;
import com.account_cics_sdk.openlegacy.Dactcs9Dactcs9Input;
import com.account_cics_sdk.openlegacy.Dactcs9Dactcs9Output;
import org.openlegacy.core.rpc.RpcSession;
import org.openlegacy.core.rpc.actions.RpcActions;

import org.openlegacy.core.annotations.services.*;
import org.openlegacy.core.annotations.OpenlegacyDesigntime;
import org.openlegacy.impl.services.ws.ServiceBinder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.context.ApplicationContext;
import org.openlegacy.utils.ActionUtil;

/**
 *  A service implementation which invokes OpenLegacy API, and returns a service output.
 *  The code below should be customize to perform a working scenario which goes through the relevant screens.
 *  Can be tested by invoking the test DeleteAccountServiceTest.
 *  The interface DeleteAccountService can be customized to enabling passing parameters to the service, and this class can consume the parameters within the relevant screens.
 */
@Service(name = "DeleteAccount")
@OpenlegacyDesigntime(editor = "WebServiceEditor")
@Component
public class DeleteAccountServiceImpl implements DeleteAccountService {

    @Autowired
    private ApplicationContext applicationContext;


    @Autowired
    private ServiceBinder serviceBinder;

    @Override
    @ServiceMethod(name = "getDeleteAccount", entities = {
            @EntityMapping(alias="dactcs9", entity=com.account_cics_sdk.openlegacy.Dactcs9.class)})
    @LogServiceUsage
    @BindInputs(endpoints = {
            @BindTo(endpoint = "dactcs9.dactcs9Input", expression = "dactcs9Input")})
    @BindOutputs(endpoints = {
            @BindFrom(endpoint = "dactcs9Output", expression = "dactcs9.dactcs9Output")})
    public DeleteAccountOut getDeleteAccount(DeleteAccountIn deleteAccountIn) throws Exception {
        DeleteAccountOut deleteAccountOut = new DeleteAccountOut();
        /* autogenerated - sessions block start*/
        ;
        RpcSession accountCicsSdkSession = applicationContext.getBean("accountCicsSdkSession", RpcSession.class);
        /* autogenerated - sessions block end */
        ;

        try {
            /* autogenerated - execution block start */;
            Dactcs9 dactcs9 = serviceBinder.bindInputs(this, "getDeleteAccount", "dactcs9", new Dactcs9(), deleteAccountIn);
            dactcs9 = accountCicsSdkSession.doAction(ActionUtil.getRpcAction(Dactcs9.class), dactcs9);
            /* autogenerated - execution block end */;

            /* autogenerated - output block start */;
            deleteAccountOut = serviceBinder.bindOutput(this, "getDeleteAccount", deleteAccountOut, new String[]{"deleteAccountIn", "dactcs9"}, deleteAccountIn, dactcs9);
            /* autogenerated - output block end */;

            return deleteAccountOut;
        } finally {
            /* autogenerated - disconnect block start */
            ;
            accountCicsSdkSession.disconnect();
            /* autogenerated - disconnect block end */
            ;
        }
    }

}
