package com.account_cics_api.openlegacy.services;

import org.apache.commons.lang3.StringUtils;
import com.account_cics_sdk.openlegacy.Ractcs9;
import com.account_cics_sdk.openlegacy.Ractcs9AccountArray;
import com.account_cics_sdk.openlegacy.Ractcs9ActiDetails;
import com.account_cics_sdk.openlegacy.Ractcs9Dfhcommarea;
import com.account_cics_sdk.openlegacy.Ractcs9InPut;
import com.account_cics_sdk.openlegacy.Ractcs9OutPut;
import org.openlegacy.core.rpc.RpcSession;
import org.openlegacy.core.rpc.actions.RpcActions;

import org.openlegacy.core.annotations.services.*;
import org.openlegacy.core.annotations.OpenlegacyDesigntime;
import org.openlegacy.impl.services.ws.ServiceBinder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.context.ApplicationContext;
import org.openlegacy.utils.ActionUtil;

/**
 *  A service implementation which invokes OpenLegacy API, and returns a service output.
 *  The code below should be customize to perform a working scenario which goes through the relevant screens.
 *  Can be tested by invoking the test ResetAccountServiceTest.
 *  The interface ResetAccountService can be customized to enabling passing parameters to the service, and this class can consume the parameters within the relevant screens.
 */
@Service(name = "ResetAccount")
@OpenlegacyDesigntime(editor = "WebServiceEditor")
@Component
public class ResetAccountServiceImpl implements ResetAccountService {

    @Autowired
    private ApplicationContext applicationContext;


    @Autowired
    private ServiceBinder serviceBinder;

    @Override
    @ServiceMethod(name = "getResetAccount", entities = {
            @EntityMapping(alias="ractcs9", entity=com.account_cics_sdk.openlegacy.Ractcs9.class)})
    @LogServiceUsage
    @BindInputs(endpoints = {
            @BindTo(endpoint = "ractcs9", expression = "ractcs9")})
    @BindOutputs(endpoints = {
            @BindFrom(endpoint = "ractcs9", expression = "ractcs9")})
    public ResetAccountOut getResetAccount(ResetAccountIn resetAccountIn) throws Exception {
        ResetAccountOut resetAccountOut = new ResetAccountOut();
        /* autogenerated - sessions block start*/
        ;
        RpcSession accountCicsSdkSession = applicationContext.getBean("accountCicsSdkSession", RpcSession.class);
        /* autogenerated - sessions block end */
        ;

        try {
            /* autogenerated - execution block start */;
            Ractcs9 ractcs9 = serviceBinder.bindInputs(this, "getResetAccount", "ractcs9", new Ractcs9(), resetAccountIn);
            ractcs9 = accountCicsSdkSession.doAction(ActionUtil.getRpcAction(Ractcs9.class), ractcs9);
            /* autogenerated - execution block end */;

            /* autogenerated - output block start */;
            resetAccountOut = serviceBinder.bindOutput(this, "getResetAccount", resetAccountOut, new String[]{"resetAccountIn", "ractcs9"}, resetAccountIn, ractcs9);
            /* autogenerated - output block end */;

            return resetAccountOut;
        } finally {
            /* autogenerated - disconnect block start */
            ;
            accountCicsSdkSession.disconnect();
            /* autogenerated - disconnect block end */
            ;
        }
    }

}
