package com.mainframe_mq_api.openlegacy.services;

import org.apache.commons.lang3.StringUtils;
import com.mainframe_mq_sdk.openlegacy.Opnact4;
import com.mainframe_mq_sdk.openlegacy.Opnact4AccountDetails;
import com.mainframe_mq_sdk.openlegacy.Opnact4AccountOut;
import com.mainframe_mq_sdk.openlegacy.Opnact4CrtAccountIn;
import org.openlegacy.core.rpc.RpcSession;
import org.openlegacy.core.rpc.actions.RpcActions;

import org.openlegacy.core.annotations.services.*;
import org.openlegacy.core.annotations.OpenlegacyDesigntime;
import org.openlegacy.impl.services.ws.ServiceBinder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.context.ApplicationContext;
import org.openlegacy.utils.ActionUtil;

/**
 *  A service implementation which invokes OpenLegacy API, and returns a service output.
 *  The code below should be customize to perform a working scenario which goes through the relevant screens.
 *  Can be tested by invoking the test AccountServiceTest.
 *  The interface AccountService can be customized to enabling passing parameters to the service, and this class can consume the parameters within the relevant screens.
 */
@Service(name = "Account")
@OpenlegacyDesigntime(editor = "WebServiceEditor")
@Component
public class AccountServiceImpl implements AccountService {

    @Autowired
    private ApplicationContext applicationContext;


    @Autowired
    private ServiceBinder serviceBinder;

    @Override
    @ServiceMethod(name = "getAccount", entities = {
            @EntityMapping(alias="opnact4", entity=com.mainframe_mq_sdk.openlegacy.Opnact4.class)})
    @LogServiceUsage
    @BindInputs(endpoints = {
            @BindTo(endpoint = "opnact4.crtAccountIn", expression = "crtAccountIn")})
    @BindOutputs(endpoints = {
            @BindFrom(endpoint = "accountOut", expression = "opnact4.accountOut")})
    public AccountOut getAccount(AccountIn accountIn) throws Exception {
        AccountOut accountOut = new AccountOut();
        /* autogenerated - sessions block start*/
        ;
        RpcSession mainframeMqSdkSession = applicationContext.getBean("mainframeMqSdkSession", RpcSession.class);
        /* autogenerated - sessions block end */
        ;

        try {
            /* autogenerated - execution block start */;
            Opnact4 opnact4 = serviceBinder.bindInputs(this, "getAccount", "opnact4", new Opnact4(), accountIn);
            opnact4 = mainframeMqSdkSession.doAction(ActionUtil.getRpcAction(Opnact4.class), opnact4);
            /* autogenerated - execution block end */;

            /* autogenerated - output block start */;
            accountOut = serviceBinder.bindOutput(this, "getAccount", accountOut, new String[]{"accountIn", "opnact4"}, accountIn, opnact4);
            /* autogenerated - output block end */;

            return accountOut;
        } finally {
            /* autogenerated - disconnect block start */
            ;
            mainframeMqSdkSession.disconnect();
            /* autogenerated - disconnect block end */
            ;
        }
    }

}
