ol:
  storedproc:
    project:
      microsoftSqlserverSpSdk:
        url: jdbc:sqlserver://solutions.openlegacy.com:1433
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        username: sa
        password: '{cipher}84ce77521448c82a4998af76909495a8793af4cda85df041f0e04678ac35b68d'
  license:
    key: 

