ol:
  ctg:
    project:
      mainframeCtgSdk:
        hostname: 192.86.32.238
        port: 13200
        code-page: CP037
        username: 
        password: 
        default-ipic-server: IPCSSL
  license:
    key: 

