ol:
  ctg:
    project:
      mainframeCtgSdk:
        hostname: mainframe.openlegacy.com
        port: 13200
        code-page: CP037
        username: 
        password: 
        default-ipic-server: IPCSSL
  license:
    key: 

