package com.cics_account_api.openlegacy.services;

import org.apache.commons.lang3.StringUtils;
import com.cics_account_api.openlegacy.Body;
import com.cics_account_api.openlegacy.Response201;
import org.openlegacy.core.annotations.services.*;
import org.openlegacy.core.annotations.OpenlegacyDesigntime;
import org.openlegacy.impl.services.ws.ServiceBinder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.context.ApplicationContext;
import org.openlegacy.utils.ActionUtil;
import com.cics_accounts_sdk.openlegacy.Gactcs9;
import org.openlegacy.core.rpc.RpcSession;
import org.openlegacy.core.rpc.actions.RpcActions;

/**
 *  A service implementation which invokes OpenLegacy API, and returns a service output.
 *  The code below should be customize to perform a working scenario which goes through the relevant screens.
 *  The interface ActivateSDCurrentAccountService can be customized to enabling passing parameters to the service, and this class can consume the parameters within the relevant screens.
 */
@Service(name = "ActivateSDCurrentAccount")
@OpenlegacyDesigntime(editor = "WebServiceEditor")
@Component
public class ActivateSDCurrentAccountServiceImpl implements ActivateSDCurrentAccountService {

    @Autowired
    private ServiceBinder serviceBinder;

    @Autowired
    private ApplicationContext applicationContext;

    @Override
    @ServiceMethod(name = "activateSDCurrentAccount", entities = { @EntityMapping(alias = "gactcs9", entity = com.cics_accounts_sdk.openlegacy.Gactcs9.class) })
    @LogServiceUsage
    @BindInputs(endpoints = {})
    @BindOutputs(endpoints = {})
    public ActivateSDCurrentAccountOut activateSDCurrentAccount(ActivateSDCurrentAccountIn activateSDCurrentAccountIn) throws Exception {
        ActivateSDCurrentAccountOut activateSDCurrentAccountOut = new ActivateSDCurrentAccountOut();
        /* autogenerated - sessions block start*/
        ;
        RpcSession cicsAccountsSdkSession = applicationContext.getBean("cicsAccountsSdkSession", RpcSession.class);
        /* autogenerated - sessions block end */
        ;
        try {
            /* autogenerated - execution block start */
            ;
            // gactcs9
            Gactcs9 gactcs9 = serviceBinder.bindInputs(this, "activateSDCurrentAccount", "gactcs9", new Gactcs9(), activateSDCurrentAccountIn);
            gactcs9 = cicsAccountsSdkSession.doAction(ActionUtil.getRpcAction(Gactcs9.class), gactcs9);
            /* autogenerated - execution block end */
            ;
            /* autogenerated - output block start */
            ;
            serviceBinder.bindOutput(this, "activateSDCurrentAccount", activateSDCurrentAccountOut, new String[] { "activateSDCurrentAccountIn", "gactcs9" }, activateSDCurrentAccountIn, gactcs9);
            /* autogenerated - output block end */
            ;
            return activateSDCurrentAccountOut;
        } finally {
            /* autogenerated - disconnect block start */
            ;
            cicsAccountsSdkSession.disconnect();
            /* autogenerated - disconnect block end */
            ;
        }
    }
}
