package com.cics_account_api.openlegacy.services;

import org.apache.commons.lang3.StringUtils;
import com.cics_account_api.openlegacy.Body;
import com.cics_account_api.openlegacy.Response200;
import java.lang.String;
import org.openlegacy.core.annotations.services.*;
import org.openlegacy.core.annotations.OpenlegacyDesigntime;
import org.openlegacy.impl.services.ws.ServiceBinder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.context.ApplicationContext;
import org.openlegacy.utils.ActionUtil;
import com.cics_accounts_sdk.openlegacy.Gactcs9;
import org.openlegacy.core.rpc.RpcSession;
import org.openlegacy.core.rpc.actions.RpcActions;
import com.cics_accounts_sdk.openlegacy.Uactcs9;

/**
 *  A service implementation which invokes OpenLegacy API, and returns a service output.
 *  The code below should be customize to perform a working scenario which goes through the relevant screens.
 *  The interface ControlCurrentAccountFulfillmentArrangementUpdateService can be customized to enabling passing parameters to the service, and this class can consume the parameters within the relevant screens.
 */
@Service(name = "ControlCurrentAccountFulfillmentArrangementUpdate")
@OpenlegacyDesigntime(editor = "WebServiceEditor")
@Component
public class ControlCurrentAccountFulfillmentArrangementUpdateServiceImpl implements ControlCurrentAccountFulfillmentArrangementUpdateService {

    @Autowired
    private ServiceBinder serviceBinder;

    @Autowired
    private ApplicationContext applicationContext;

    @Override
    @ServiceMethod(name = "controlCurrentAccountFulfillmentArrangementUpdate", entities = {})
    @LogServiceUsage
    @BindInputs(endpoints = {})
    @BindOutputs(endpoints = {})
    public ControlCurrentAccountFulfillmentArrangementUpdateOut controlCurrentAccountFulfillmentArrangementUpdate(ControlCurrentAccountFulfillmentArrangementUpdateIn controlCurrentAccountFulfillmentArrangementUpdateIn) throws Exception {
        ControlCurrentAccountFulfillmentArrangementUpdateOut controlCurrentAccountFulfillmentArrangementUpdateOut = new ControlCurrentAccountFulfillmentArrangementUpdateOut();
        /* autogenerated - sessions block start*/
        ;
        /* autogenerated - sessions block end */
        ;
        try {
            /* autogenerated - execution block start */
            ;
            /* autogenerated - execution block end */
            ;
            /* autogenerated - output block start */
            ;
            serviceBinder.bindOutput(this, "controlCurrentAccountFulfillmentArrangementUpdate", controlCurrentAccountFulfillmentArrangementUpdateOut, new String[] { "controlCurrentAccountFulfillmentArrangementUpdateIn" }, controlCurrentAccountFulfillmentArrangementUpdateIn);
            /* autogenerated - output block end */
            ;
            return controlCurrentAccountFulfillmentArrangementUpdateOut;
        } finally {
            /* autogenerated - disconnect block start */
            ;
            /* autogenerated - disconnect block end */
            ;
        }
    }
}
