package com.cics_account_api.openlegacy.services;

import org.apache.commons.lang3.StringUtils;
import com.cics_account_api.openlegacy.Body;
import com.cics_account_api.openlegacy.Response200;
import java.lang.String;
import org.openlegacy.core.annotations.services.*;
import org.openlegacy.core.annotations.OpenlegacyDesigntime;
import org.openlegacy.impl.services.ws.ServiceBinder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.context.ApplicationContext;
import org.openlegacy.utils.ActionUtil;
import com.cics_accounts_sdk.openlegacy.Uactcs9;
import org.openlegacy.core.rpc.RpcSession;
import org.openlegacy.core.rpc.actions.RpcActions;

/**
 *  A service implementation which invokes OpenLegacy API, and returns a service output.
 *  The code below should be customize to perform a working scenario which goes through the relevant screens.
 *  The interface ExchangeCurrentAccountFulfillmentArrangementAccountLienUpdateService can be customized to enabling passing parameters to the service, and this class can consume the parameters within the relevant screens.
 */
@Service(name = "ExchangeCurrentAccountFulfillmentArrangementAccountLienUpdate")
@OpenlegacyDesigntime(editor = "WebServiceEditor")
@Component
public class ExchangeCurrentAccountFulfillmentArrangementAccountLienUpdateServiceImpl implements ExchangeCurrentAccountFulfillmentArrangementAccountLienUpdateService {

    @Autowired
    private ServiceBinder serviceBinder;

    @Autowired
    private ApplicationContext applicationContext;

    @Override
    @ServiceMethod(name = "exchangeCurrentAccountFulfillmentArrangementAccountLienUpdate", entities = { @EntityMapping(alias = "uactcs9", entity = com.cics_accounts_sdk.openlegacy.Uactcs9.class) })
    @LogServiceUsage
    @BindInputs(endpoints = { @BindTo(endpoint = "uactcs9.dfhcommarea.updateIn.inputRecord.actiAccountId", expression = "sdReferenceId"), @BindTo(endpoint = "uactcs9.dfhcommarea.updateIn.inputRecord.actiCustomerId", expression = "crReferenceId"), @BindTo(endpoint = "uactcs9.dfhcommarea.updateIn.inputRecord", expression = "body.accountLienExchangeActionTaskRecord") })
    @BindOutputs(endpoints = { @BindFrom(endpoint = "response200.accountLienExchangeActionTaskRecord", expression = "uactcs9.dfhcommarea.updateOut.outputRecord") })
    public ExchangeCurrentAccountFulfillmentArrangementAccountLienUpdateOut exchangeCurrentAccountFulfillmentArrangementAccountLienUpdate(ExchangeCurrentAccountFulfillmentArrangementAccountLienUpdateIn exchangeCurrentAccountFulfillmentArrangementAccountLienUpdateIn) throws Exception {
        ExchangeCurrentAccountFulfillmentArrangementAccountLienUpdateOut exchangeCurrentAccountFulfillmentArrangementAccountLienUpdateOut = new ExchangeCurrentAccountFulfillmentArrangementAccountLienUpdateOut();
        /* autogenerated - sessions block start*/
        ;
        RpcSession cicsAccountsSdkSession = applicationContext.getBean("cicsAccountsSdkSession", RpcSession.class);
        /* autogenerated - sessions block end */
        ;
        try {
            /* autogenerated - execution block start */
            ;
            // uactcs9
            Uactcs9 uactcs9 = serviceBinder.bindInputs(this, "exchangeCurrentAccountFulfillmentArrangementAccountLienUpdate", "uactcs9", new Uactcs9(), exchangeCurrentAccountFulfillmentArrangementAccountLienUpdateIn);
            uactcs9 = cicsAccountsSdkSession.doAction(ActionUtil.getRpcAction(Uactcs9.class), uactcs9);
            /* autogenerated - execution block end */
            ;
            /* autogenerated - output block start */
            ;
            serviceBinder.bindOutput(this, "exchangeCurrentAccountFulfillmentArrangementAccountLienUpdate", exchangeCurrentAccountFulfillmentArrangementAccountLienUpdateOut, new String[] { "exchangeCurrentAccountFulfillmentArrangementAccountLienUpdateIn", "uactcs9" }, exchangeCurrentAccountFulfillmentArrangementAccountLienUpdateIn, uactcs9);
            /* autogenerated - output block end */
            ;
            return exchangeCurrentAccountFulfillmentArrangementAccountLienUpdateOut;
        } finally {
            /* autogenerated - disconnect block start */
            ;
            cicsAccountsSdkSession.disconnect();
            /* autogenerated - disconnect block end */
            ;
        }
    }
}
