package com.cics_account_api.openlegacy.services;

import org.apache.commons.lang3.StringUtils;
import com.cics_account_api.openlegacy.Response200;
import java.lang.String;

import org.openlegacy.core.annotations.services.*;
import org.openlegacy.core.annotations.OpenlegacyDesigntime;
import org.openlegacy.impl.services.ws.ServiceBinder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.context.ApplicationContext;
import org.openlegacy.utils.ActionUtil;

/**
 *  A service implementation which invokes OpenLegacy API, and returns a service output.
 *  The code below should be customize to perform a working scenario which goes through the relevant screens.
 *  The interface RetrieveCurrentAccountFulfillmentArrangementAccountSweepService can be customized to enabling passing parameters to the service, and this class can consume the parameters within the relevant screens.
 */
@Service(name = "RetrieveCurrentAccountFulfillmentArrangementAccountSweep")
@OpenlegacyDesigntime(editor = "WebServiceEditor")
@Component
public class RetrieveCurrentAccountFulfillmentArrangementAccountSweepServiceImpl implements RetrieveCurrentAccountFulfillmentArrangementAccountSweepService {


    @Autowired
    private ServiceBinder serviceBinder;

    @Override
    @ServiceMethod(name = "retrieveCurrentAccountFulfillmentArrangementAccountSweep")
    @LogServiceUsage
    @BindInputs(endpoints = {})
    @BindOutputs(endpoints = {})
    public RetrieveCurrentAccountFulfillmentArrangementAccountSweepOut retrieveCurrentAccountFulfillmentArrangementAccountSweep(RetrieveCurrentAccountFulfillmentArrangementAccountSweepIn retrieveCurrentAccountFulfillmentArrangementAccountSweepIn) throws Exception {
        RetrieveCurrentAccountFulfillmentArrangementAccountSweepOut retrieveCurrentAccountFulfillmentArrangementAccountSweepOut = new RetrieveCurrentAccountFulfillmentArrangementAccountSweepOut();
        /* autogenerated - sessions block start*/
        ;
        /* autogenerated - sessions block end */
        ;

        try {
            /* autogenerated - execution block start */;
            /* autogenerated - execution block end */;

            /* autogenerated - output block start */;
            retrieveCurrentAccountFulfillmentArrangementAccountSweepOut = serviceBinder.bindOutput(this, "retrieveCurrentAccountFulfillmentArrangementAccountSweep", retrieveCurrentAccountFulfillmentArrangementAccountSweepOut, new String[]{"retrieveCurrentAccountFulfillmentArrangementAccountSweepIn"}, retrieveCurrentAccountFulfillmentArrangementAccountSweepIn);
            /* autogenerated - output block end */;

            return retrieveCurrentAccountFulfillmentArrangementAccountSweepOut;
        } finally {
            /* autogenerated - disconnect block start */
            ;
            /* autogenerated - disconnect block end */
            ;
        }
    }

}
