package com.cics_account_api.openlegacy.services;

import org.apache.commons.lang3.StringUtils;
import com.cics_account_api.openlegacy.Body;
import com.cics_account_api.openlegacy.Response200;
import java.lang.String;
import org.openlegacy.core.annotations.services.*;
import org.openlegacy.core.annotations.OpenlegacyDesigntime;
import org.openlegacy.impl.services.ws.ServiceBinder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.context.ApplicationContext;
import org.openlegacy.utils.ActionUtil;
import com.cics_accounts_sdk.openlegacy.Uactcs9;
import org.openlegacy.core.rpc.RpcSession;
import org.openlegacy.core.rpc.actions.RpcActions;

/**
 *  A service implementation which invokes OpenLegacy API, and returns a service output.
 *  The code below should be customize to perform a working scenario which goes through the relevant screens.
 *  The interface UpdateCurrentAccountFulfillmentArrangementAccountLienService can be customized to enabling passing parameters to the service, and this class can consume the parameters within the relevant screens.
 */
@Service(name = "UpdateCurrentAccountFulfillmentArrangementAccountLien")
@OpenlegacyDesigntime(editor = "WebServiceEditor")
@Component
public class UpdateCurrentAccountFulfillmentArrangementAccountLienServiceImpl implements UpdateCurrentAccountFulfillmentArrangementAccountLienService {

    @Autowired
    private ServiceBinder serviceBinder;

    @Autowired
    private ApplicationContext applicationContext;

    @Override
    @ServiceMethod(name = "updateCurrentAccountFulfillmentArrangementAccountLien", entities = {})
    @LogServiceUsage
    @BindInputs(endpoints = {})
    @BindOutputs(endpoints = {})
    public UpdateCurrentAccountFulfillmentArrangementAccountLienOut updateCurrentAccountFulfillmentArrangementAccountLien(UpdateCurrentAccountFulfillmentArrangementAccountLienIn updateCurrentAccountFulfillmentArrangementAccountLienIn) throws Exception {
        UpdateCurrentAccountFulfillmentArrangementAccountLienOut updateCurrentAccountFulfillmentArrangementAccountLienOut = new UpdateCurrentAccountFulfillmentArrangementAccountLienOut();
        /* autogenerated - sessions block start*/
        ;
        /* autogenerated - sessions block end */
        ;
        try {
            /* autogenerated - execution block start */
            ;
            /* autogenerated - execution block end */
            ;
            /* autogenerated - output block start */
            ;
            serviceBinder.bindOutput(this, "updateCurrentAccountFulfillmentArrangementAccountLien", updateCurrentAccountFulfillmentArrangementAccountLienOut, new String[] { "updateCurrentAccountFulfillmentArrangementAccountLienIn" }, updateCurrentAccountFulfillmentArrangementAccountLienIn);
            /* autogenerated - output block end */
            ;
            return updateCurrentAccountFulfillmentArrangementAccountLienOut;
        } finally {
            /* autogenerated - disconnect block start */
            ;
            /* autogenerated - disconnect block end */
            ;
        }
    }
}
