package com.account_db2_api.openlegacy.services;

import org.apache.commons.lang3.StringUtils;
import com.account_db2_sdk.openlegacy.Dactsql;
import org.openlegacy.core.rpc.RpcSession;
import org.openlegacy.core.rpc.actions.RpcActions;

import org.openlegacy.core.annotations.services.*;
import org.openlegacy.core.annotations.OpenlegacyDesigntime;
import org.openlegacy.impl.services.ws.ServiceBinder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.context.ApplicationContext;
import org.openlegacy.utils.ActionUtil;

/**
 *  A service implementation which invokes OpenLegacy API, and returns a service output.
 *  The code below should be customize to perform a working scenario which goes through the relevant screens.
 *  Can be tested by invoking the test DeleteAccountServiceTest.
 *  The interface DeleteAccountService can be customized to enabling passing parameters to the service, and this class can consume the parameters within the relevant screens.
 */
@Service(name = "DeleteAccount")
@OpenlegacyDesigntime(editor = "WebServiceEditor")
@Component
public class DeleteAccountServiceImpl implements DeleteAccountService {

    @Autowired
    private ApplicationContext applicationContext;


    @Autowired
    private ServiceBinder serviceBinder;

    @Override
    @ServiceMethod(name = "getDeleteAccount", entities = {
            @EntityMapping(alias="dactsql", entity=com.account_db2_sdk.openlegacy.Dactsql.class)})
    @LogServiceUsage
    @BindInputs(endpoints = {
            @BindTo(endpoint = "dactsql.accountId", expression = "accountId")})
    @BindOutputs(endpoints = {
            @BindFrom(endpoint = "dactsql", expression = "dactsql")})
    public DeleteAccountOut getDeleteAccount(DeleteAccountIn deleteAccountIn) throws Exception {
        DeleteAccountOut deleteAccountOut = new DeleteAccountOut();
        /* autogenerated - sessions block start*/
        ;
        RpcSession accountDb2SdkSession = applicationContext.getBean("accountDb2SdkSession", RpcSession.class);
        /* autogenerated - sessions block end */
        ;

        try {
            /* autogenerated - execution block start */;
            Dactsql dactsql = serviceBinder.bindInputs(this, "getDeleteAccount", "dactsql", new Dactsql(), deleteAccountIn);
            dactsql = accountDb2SdkSession.doAction(ActionUtil.getRpcAction(Dactsql.class), dactsql);
            /* autogenerated - execution block end */;

            /* autogenerated - output block start */;
            deleteAccountOut = serviceBinder.bindOutput(this, "getDeleteAccount", deleteAccountOut, new String[]{"deleteAccountIn", "dactsql"}, deleteAccountIn, dactsql);
            /* autogenerated - output block end */;

            return deleteAccountOut;
        } finally {
            /* autogenerated - disconnect block start */
            ;
            accountDb2SdkSession.disconnect();
            /* autogenerated - disconnect block end */
            ;
        }
    }

}
