package com.account_db2_api.openlegacy.services;

import org.apache.commons.lang3.StringUtils;
import com.account_db2_sdk.openlegacy.Gactsql;
import com.account_db2_sdk.openlegacy.Gactsql.ResultSet;
import org.openlegacy.core.rpc.RpcSession;
import org.openlegacy.core.rpc.actions.RpcActions;

import org.openlegacy.core.annotations.services.*;
import org.openlegacy.core.annotations.OpenlegacyDesigntime;
import org.openlegacy.impl.services.ws.ServiceBinder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.context.ApplicationContext;
import org.openlegacy.utils.ActionUtil;

/**
 *  A service implementation which invokes OpenLegacy API, and returns a service output.
 *  The code below should be customize to perform a working scenario which goes through the relevant screens.
 *  Can be tested by invoking the test GetAccountServiceTest.
 *  The interface GetAccountService can be customized to enabling passing parameters to the service, and this class can consume the parameters within the relevant screens.
 */
@Service(name = "GetAccount")
@OpenlegacyDesigntime(editor = "WebServiceEditor")
@Component
public class GetAccountServiceImpl implements GetAccountService {

    @Autowired
    private ApplicationContext applicationContext;


    @Autowired
    private ServiceBinder serviceBinder;

    @Override
    @ServiceMethod(name = "getGetAccount", entities = {
            @EntityMapping(alias="gactsql", entity=com.account_db2_sdk.openlegacy.Gactsql.class)})
    @LogServiceUsage
    @BindInputs(endpoints = {
            @BindTo(endpoint = "gactsql.accountId", expression = "accountId")})
    @BindOutputs(endpoints = {
            @BindFrom(endpoint = "resultSet", expression = "gactsql.resultSet")})
    public GetAccountOut getGetAccount(GetAccountIn getAccountIn) throws Exception {
        GetAccountOut getAccountOut = new GetAccountOut();
        /* autogenerated - sessions block start*/
        ;
        RpcSession accountDb2SdkSession = applicationContext.getBean("accountDb2SdkSession", RpcSession.class);
        /* autogenerated - sessions block end */
        ;

        try {
            /* autogenerated - execution block start */;
            Gactsql gactsql = serviceBinder.bindInputs(this, "getGetAccount", "gactsql", new Gactsql(), getAccountIn);
            gactsql = accountDb2SdkSession.doAction(ActionUtil.getRpcAction(Gactsql.class), gactsql);
            /* autogenerated - execution block end */;

            /* autogenerated - output block start */;
            getAccountOut = serviceBinder.bindOutput(this, "getGetAccount", getAccountOut, new String[]{"getAccountIn", "gactsql"}, getAccountIn, gactsql);
            /* autogenerated - output block end */;

            return getAccountOut;
        } finally {
            /* autogenerated - disconnect block start */
            ;
            accountDb2SdkSession.disconnect();
            /* autogenerated - disconnect block end */
            ;
        }
    }

}
