package com.account_db2_api.openlegacy.services;

import org.apache.commons.lang3.StringUtils;
import com.account_db2_sdk.openlegacy.Oactsql;
import java.math.BigDecimal;
import org.openlegacy.core.rpc.RpcSession;
import org.openlegacy.core.rpc.actions.RpcActions;

import org.openlegacy.core.annotations.services.*;
import org.openlegacy.core.annotations.OpenlegacyDesigntime;
import org.openlegacy.impl.services.ws.ServiceBinder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.context.ApplicationContext;
import org.openlegacy.utils.ActionUtil;

/**
 *  A service implementation which invokes OpenLegacy API, and returns a service output.
 *  The code below should be customize to perform a working scenario which goes through the relevant screens.
 *  Can be tested by invoking the test OpenAccountServiceTest.
 *  The interface OpenAccountService can be customized to enabling passing parameters to the service, and this class can consume the parameters within the relevant screens.
 */
@Service(name = "OpenAccount")
@OpenlegacyDesigntime(editor = "WebServiceEditor")
@Component
public class OpenAccountServiceImpl implements OpenAccountService {

    @Autowired
    private ApplicationContext applicationContext;


    @Autowired
    private ServiceBinder serviceBinder;

    @Override
    @ServiceMethod(name = "getOpenAccount", entities = {
            @EntityMapping(alias="oactsql", entity=com.account_db2_sdk.openlegacy.Oactsql.class)})
    @LogServiceUsage
    @BindInputs(endpoints = {
            @BindTo(endpoint = "oactsql.accountId", expression = "accountId"),
            @BindTo(endpoint = "oactsql.customerId", expression = "customerId"),
            @BindTo(endpoint = "oactsql.customerName", expression = "customerName"),
            @BindTo(endpoint = "oactsql.iban", expression = "iban"),
            @BindTo(endpoint = "oactsql.bnkId", expression = "bnkId"),
            @BindTo(endpoint = "oactsql.brnchId", expression = "brnchId"),
            @BindTo(endpoint = "oactsql.cntryCd", expression = "cntryCd"),
            @BindTo(endpoint = "oactsql.typcd", expression = "typcd"),
            @BindTo(endpoint = "oactsql.subTypcd", expression = "subTypcd"),
            @BindTo(endpoint = "oactsql.typeName", expression = "typeName"),
            @BindTo(endpoint = "oactsql.typeDescription", expression = "typeDescription"),
            @BindTo(endpoint = "oactsql.balance", expression = "balance"),
            @BindTo(endpoint = "oactsql.currency", expression = "currency"),
            @BindTo(endpoint = "oactsql.crtDt", expression = "crtDt"),
            @BindTo(endpoint = "oactsql.updtDt", expression = "updtDt"),
            @BindTo(endpoint = "oactsql.locked", expression = "locked")})
    @BindOutputs(endpoints = {
            @BindFrom(endpoint = "accountId", expression = "oactsql.accountId"),
            @BindFrom(endpoint = "customerId", expression = "oactsql.customerId"),
            @BindFrom(endpoint = "customerName", expression = "oactsql.customerName"),
            @BindFrom(endpoint = "iban", expression = "oactsql.iban"),
            @BindFrom(endpoint = "bnkId", expression = "oactsql.bnkId"),
            @BindFrom(endpoint = "brnchId", expression = "oactsql.brnchId"),
            @BindFrom(endpoint = "cntryCd", expression = "oactsql.cntryCd"),
            @BindFrom(endpoint = "typcd", expression = "oactsql.typcd"),
            @BindFrom(endpoint = "subTypcd", expression = "oactsql.subTypcd"),
            @BindFrom(endpoint = "typeName", expression = "oactsql.typeName"),
            @BindFrom(endpoint = "typeDescription", expression = "oactsql.typeDescription"),
            @BindFrom(endpoint = "balance", expression = "oactsql.balance"),
            @BindFrom(endpoint = "currency", expression = "oactsql.currency"),
            @BindFrom(endpoint = "crtDt", expression = "oactsql.crtDt"),
            @BindFrom(endpoint = "updtDt", expression = "oactsql.updtDt"),
            @BindFrom(endpoint = "locked", expression = "oactsql.locked")})
    public OpenAccountOut getOpenAccount(OpenAccountIn openAccountIn) throws Exception {
        OpenAccountOut openAccountOut = new OpenAccountOut();
        /* autogenerated - sessions block start*/
        ;
        RpcSession accountDb2SdkSession = applicationContext.getBean("accountDb2SdkSession", RpcSession.class);
        /* autogenerated - sessions block end */
        ;

        try {
            /* autogenerated - execution block start */;
            Oactsql oactsql = serviceBinder.bindInputs(this, "getOpenAccount", "oactsql", new Oactsql(), openAccountIn);
            oactsql = accountDb2SdkSession.doAction(ActionUtil.getRpcAction(Oactsql.class), oactsql);
            /* autogenerated - execution block end */;

            /* autogenerated - output block start */;
            openAccountOut = serviceBinder.bindOutput(this, "getOpenAccount", openAccountOut, new String[]{"openAccountIn", "oactsql"}, openAccountIn, oactsql);
            /* autogenerated - output block end */;

            return openAccountOut;
        } finally {
            /* autogenerated - disconnect block start */
            ;
            accountDb2SdkSession.disconnect();
            /* autogenerated - disconnect block end */
            ;
        }
    }

}
